# Generated by Django 5.1 on 2024-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
